server:
  port: 7002

spring:
  application:
    name: proj-dashboard

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

management:
  endpoint:
    web:
      exposure:
        include: "*"