server:
  port: 7003
  servlet:
    context-path: /proj-broadcast

spring:
  application:
    name: eureka-client-proj-broadcast
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

feign:
  hystrix:
    enable: true

management:
  endpoint:
    web:
      exposure:
        include: "*"

projconf:
  kafka:
    topic: proj-search-mysql-data