server:
  port: 9000
spring:
  application:
    name: proj-geteway
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

zuul:
  prefix: /rio
  routes:
    #name
    producer:
      #** multi layer map
      path: /proj-producer/**
      serviceId: eureka-client-proj-producer
      #ignore prefix or not
      #127.0.0.1:9000/rio/proj-producer/create/project
      strip-prefix: false
    search:
      path: /proj-search/**
      seviceId: eureka-client-proj-search
      strip-prefix: false
      #127.0.0.1:9000/rio/proj-search/fetchAds
    broadcast:
      path: /proj-broadcast/**
      serviceId: eureka-client-proj-broadcast
      strip-prefix: false
